title: Blog de Jose Ramón Tauste
description: > # this means to ignore newlines until "baseurl:"
  Hola soy Jose Ramón Tauste estudiante de ciberseguridad en el instituto ies el caminás y publicaré en este blog mis propios trabajos.
permalink: ':title/'
baseurl: "/alutau.github.io.3" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/joseramontauste #if your site has a twitter account, enter it here

# Author Settings
author: Jose Ramón Tauste # add your name
author-img: david-freeman.jpg # add your photo
about-author: Hola soy Jose Ramón Tauste estudiante de ciberseguridad en el instituto ies el caminás
              y publicaré en este blog mis trabajos. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: alutau # add your Github handle
social-linkedin: https://www.linkedin.com/in/jose-ram%C3%B3n-tauste-candel-b9a0b2198/ # add your Linkedin handle
social-email: alutau561@ieselcaminas.org # add your Email address

# Disqus
discus-identifier: alutau # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
